# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "grpc", "~> 1.19"
gem "grpc-tools", "~> 1.19"

gem "benchmark-ips", "~> 2.7"
gem "redis"