version: "3"
services:
  prom:
    image: prom/prometheus:v2.7.1
    volumes:
     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./tmp/grafana:/var/lib/grafana
    ports:
     - "3000:3000"
