# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "types.ReserveResult" do
    optional :result, :enum, 1, "types.ReserveResult.Result"
    optional :job, :message, 2, "types.Job"
  end
  add_enum "types.ReserveResult.Result" do
    value :NONE, 0
    value :RESERVED, 1
  end
  add_message "types.JobId" do
    optional :id, :string, 1
  end
  add_message "types.Job" do
    optional :id, :message, 1, "types.JobId"
    optional :priority, :int32, 2
    optional :payload, :bytes, 3
  end
  add_message "types.QueuedJob" do
    optional :job, :message, 1, "types.Job"
    optional :enqueued_at, :message, 2, "google.protobuf.Timestamp"
    optional :concurrency, :message, 3, "types.ConcurrencyControl"
  end
  add_message "types.ConcurrencyControl" do
    optional :key, :string, 1
    optional :max_concurrency, :int32, 2
    optional :on_limit, :enum, 3, "types.ConcurrencyControl.OnLimit"
  end
  add_enum "types.ConcurrencyControl.OnLimit" do
    value :RETRY, 0
    value :DROP, 1
  end
  add_message "types.JobEnqueueRequest" do
    optional :priority, :int32, 1
    optional :payload, :bytes, 2
    optional :concurrency, :message, 3, "types.ConcurrencyControl"
  end
end

module Types
  ReserveResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ReserveResult").msgclass
  ReserveResult::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ReserveResult.Result").enummodule
  JobId = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.JobId").msgclass
  Job = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.Job").msgclass
  QueuedJob = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.QueuedJob").msgclass
  ConcurrencyControl = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ConcurrencyControl").msgclass
  ConcurrencyControl::OnLimit = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ConcurrencyControl.OnLimit").enummodule
  JobEnqueueRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.JobEnqueueRequest").msgclass
end
